#config_version=6

mode:
  start_events: start_mode_bumpers
  stop_events: stop_mode_bumpers
  priority: 200

shots:
  bumper_front:
    switch: s_frontbumper
  bumper_back:
    switch: s_backbumper

shot_groups:
  bumpers:
    shots: bumper_front, bumper_back

variable_player:
  bumpers_hit:
    score: 150