#config_version=6

ball_devices:
  bd_trough:
    ball_switches: s_trough_ball1, s_trough_ball2, s_trough_ball3
    jam_switch: s_trough_jam
    eject_coil: c_trough_eject
    eject_targets: bd_plunger
    confirm_eject_type: target
    tags: trough, home, drain
    eject_timeouts: 3000ms
  bd_plunger:
    ball_switches: s_plunger
    eject_coil: c_autoplunger
    player_controlled_eject_event: s_launch_active
    tags: plunger
  bd_vuk:
    ball_switches: s_vuk
    eject_coil: c_vuk
    eject_timeouts: 2s
  bd_scoop:
    ball_switches: s_scoop
    eject_coil: c_scoop
    eject_timeouts: 2s     